<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Product Category Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <?php
                        $product_page = '#0';
                        if(module_exists('admin-product'))
                            $product_page = $this->router->to('adminProduct');
                    ?>
                    <li class="breadcrumb-item"><a href="<?= $product_page ?>">Product</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminProductCategory') ?>">Category</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field('name'); ?>
                                <?= $form->field('slug'); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field('parent', $opts['parent']); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('content'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <?php if(isset($x_fields['left-bottom-left'])): ?>
                                    <?php foreach($x_fields['left-bottom-left'] as $fld): ?>
                                        <?= $form->field($fld); ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-6">
                                <?php if(isset($x_fields['left-bottom-right'])): ?>
                                    <?php foreach($x_fields['left-bottom-right'] as $fld): ?>
                                        <?= $form->field($fld); ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <?php if(isset($x_fields['right-top'])): ?>
                            <?php foreach($x_fields['right-top'] as $fld): ?>
                                <?= $form->field($fld); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        
                        <?= $this->partial('site-meta/meta'); ?>

                        <?php if(isset($x_fields['right-bottom'])): ?>
                            <?php foreach($x_fields['right-bottom'] as $fld): ?>
                                <?= $form->field($fld); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>